### ISSUE TITLE
RdfUnit not working

### ISSUE THREAD

**Issue by vemonet** [MaastrichtU-IDS/dqa-pipeline#3]
The 2 other project works well, but RdfUnit crashes when run

Here is the command:
```shell
docker run --rm -i -v /data/dqa:/data dqa-rdfunit -d "http://sparql.wikipathways.org/" -e "http://sparql.wikipathways.org/" -f /data/ -o ttl
```

Here is the error:
```shell
[WARN  NamespaceStatistics] Undefined namespace in LOV or schemaDecl.csv: http://vocabularies.wikipathways.org/wp#
[ERROR SchemaSource] Cannot load ontology: http://xmlns.com/foaf/0.1/ 
org.aksw.rdfunit.io.reader.RdfReaderException: Cannot read from any reader: 
org.apache.jena.riot.RiotException: Failed to determine the content type: (URI=http://xmlns.com/foaf/0.1/ : stream=text/html)
	at org.aksw.rdfunit.io.reader.RdfFirstSuccessReader.read(RdfFirstSuccessReader.java:50)
	at org.aksw.rdfunit.sources.SchemaSource.initModel(SchemaSource.java:75)
	at org.aksw.rdfunit.sources.SchemaSource.getModel(SchemaSource.java:34)
	at org.aksw.rdfunit.tests.generators.TestGeneratorExecutor.generateTestSuite(TestGeneratorExecutor.java:104)
	at org.aksw.rdfunit.validate.cli.ValidateCLI.main(ValidateCLI.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
[ERROR TestGeneratorExecutor] Trying to generate tests for http://xmlns.com/foaf/0.1/ but cannot read source
[INFO  SimpleTestExecutorMonitor] Testing http://sparql.wikipathways.org
[INFO  SimpleTestExecutorMonitor] Tests run: 0, Failed: 0, Timeout: 0, Error: 0. Individual Errors: 0
[INFO  ValidateCLI] Results stored in: /data/results/sparql.wikipathways.org.aggregatedTestCaseResult.*
```

Seems like the http://xmlns.com/foaf/0.1/ processing fail

**Comment by vemonet** [comment]
https://github.com/MaastrichtU-IDS/dqa-pipeline/commit/1bb5a51141bf9fe50e00945fd9ce4ef38ee53781
